feat: Potential exploiters agent template
NethermindEth/general-agents-module pull request #35
Opened 2022-05-26 08:52 UTC by rohit-goswami

2022-06-16 14:31 UTC, e1Ru1o commented on src/potential.exploiters.ts
> +          findings.push(findingGenerator({ from: trace.action.from, contractAddress }));
it would be nice to include the list of hex present in the bytecode

2022-06-18 08:57 UTC, rohit-goswami reviewed
list of hex present added to findings.

2022-07-06 14:41 UTC, e1Ru1o requested changes

2022-07-06 14:41 UTC, e1Ru1o commented on src/potential.exploiters.ts
> +          findings.push(findingGenerator({ from: trace.action.from, contractAddress, suspiciousHexValues: hex_present }));
`metedata` only allows strings
```suggestion
          findings.push(findingGenerator({ from: trace.action.from, contractAddress, suspiciousHexValues: hex_present.toString() }));
```

2022-07-06 14:41 UTC, e1Ru1o commented on src/potential.exploiters.spec.ts
> +    findings = findings.concat(await handleTransaction(txEvent2));
This is not correct, you must check the result of each `txEvent` separately. Let me show why it is not correct:

if your expected concat is:
`expected_concat = [ A, B, C, D, E ]`

that concat may be achieved in multiple ways
```
[ A ], [ B, C, D, E ] or
[ A, B, C ], [ D, E ] or
[], [ A, B, C, D, E ] or
...
```

this seems to not apply to your case because you are expecting `[]` but it is not a good practice in general, so please do the checks individually.

2023-07-14 23:22 UTC, closed without merging